version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.12
    commands:
      - echo Installing SAM CLI
      - pip install aws-sam-cli
      - echo Installing dependencies
      - npm install

  pre_build:
    commands:
      - echo Running tests
      - npm test
      - echo Running linter
      - npm run lint

  build:
    commands:
      - echo Building SAM application
      - sam build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging application
      - |
        sam package \
          --s3-bucket ${BUCKET_NAME} \
          --output-template-file packaged-template.yaml

artifacts:
  files:
    - packaged-template.yaml
    - buildspec.yml

cache:
  paths:
    - 'node_modules/**/*'
    - '.aws-sam/**/*'
