version: '3.8'

services:
  # Local DynamoDB
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: slack2backlog-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  # LocalStack for SQS and Secrets Manager
  localstack:
    image: localstack/localstack:latest
    container_name: slack2backlog-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,secretsmanager,ssm,lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-northeast-1
      - LAMBDA_EXECUTOR=docker
    volumes:
      - "./docker/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/localstack-init.sh:/docker-entrypoint-initaws.d/init.sh"

  # DynamoDB Admin UI
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: slack2backlog-dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=ap-northeast-1
    depends_on:
      - dynamodb-local
